/*
 * This file is automatically generated by codegen
 */
/*
 * Copyring (C) 2016 Zhen Huang
 */

#define GCONF_ENABLE_INTERNALS
#define _GNU_SOURCE
#include <dlfcn.h>
#include <gconf/gconf-client.h>
#include <gconf/gconf.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <unistd.h>
#include <fcntl.h>
#include <execinfo.h>
#include <semaphore.h>
#include <unistd.h>
#include <sys/syscall.h>
#include "../kernel_logger/gconf_msg.h"

extern char **backtrace_symbols_ex(void *const *buffer, int size);

sem_t lock;
int prt_backtrace = 0;
#define LOCAL_LOG

char trace_file_name[512];

#ifndef MAX_PATH
#define MAX_PATH 512
#endif

#ifndef min
#define min(x, y) (x > y? y : x)
#endif

static char *cmd2str(int cmd)
{
	static char *cmd_names[] = {
		"UNKNOWN",
		"GET_VALUE",
		"SET_VALUE",
		"GET_VALUE_LIST",
		"SET_VALUE_LIST",
	};
	if (cmd < sizeof(cmd_names)/sizeof(cmd_names[0]))
		return cmd_names[cmd];
	else
		return NULL;
}

static int
get_file(int pid, char *name, char *buf)
{
	char file[80];
	int fd, num_read;

	sprintf(file, "/proc/%d/%s", pid, name);
	if ((fd = open(file, O_RDONLY, 0)) < 0)
		return -1;
	if ((num_read = read(fd, buf, MAX_PATH)) < 0)
		return -1;
	if (num_read > 0)
		buf[num_read - 1] = 0;
	close(fd);
	return num_read;
}

static const char *
get_proc_name(int pid, char *buf)
{
	if (get_file(pid, "cmdline", buf) > 0)
		return buf;
	else
		return NULL;
}

/*
 * transfer data in GConfValue into the buffer pointed by ptr
 */
int get_gconfvalue(const GConfValue *value, char *ptr, int size)
{
	int ival = 0;
	double fval = 0.0;
	int bval = 0;
	int len;
	const char *str = NULL;

	switch(value->type) {
	case GCONF_VALUE_INT:
		len = sizeof(int);
		if (len < size) {
			ival = gconf_value_get_int(value);
			memcpy(ptr, &ival, sizeof(int));
		} else
			len = 0;
		break;
	case GCONF_VALUE_BOOL:
		len = sizeof(int);
		if (len < size) {
			bval = gconf_value_get_bool(value);
			memcpy(ptr, &bval, sizeof(int));
		} else
			len = 0;
		break;
	case GCONF_VALUE_FLOAT:
		len = sizeof(double);
		if (len < size) {
			fval = gconf_value_get_float(value);
			memcpy(ptr, &fval, sizeof(double));
		} else
			len = 0;
		break;
	case GCONF_VALUE_STRING:
		str = gconf_value_get_string(value);
		if (str) {
			strncpy(ptr, str, size);
			ptr[size - 1] = '\0';
			len = strlen(ptr);
		} else {
			*ptr = '\0';
			len = 0;
		}
		break;
	default:
		*ptr = '\0';
		len = 0;
		break;
	}
	return len;
}

int set_value(char *ptr, int size, int type, const char *value)
{
	int len;

	switch(type) {
	case GCONF_VALUE_INT:
		len = sizeof(int);
		if (len < size)
			memcpy(ptr, value, sizeof(int));
		else
			len = 0;
		break;
	case GCONF_VALUE_BOOL:
		len = sizeof(int);
		if (len < size)
			memcpy(ptr, value, sizeof(int));
		else
			len = 0;
		break;
	case GCONF_VALUE_FLOAT:
		len = sizeof(double);
		if (len < size)
			memcpy(ptr, value, sizeof(double));
		else
			len = 0;
		break;
	case GCONF_VALUE_STRING:
		strncpy(ptr, value, size);
		ptr[size - 1] = '\0';
		len = min(size - 1, strlen(value));
		break;
	default:
		*ptr = '\0';
		len = 0;
		break;
	}
	return len;
}

typedef struct {
	char *ptr;
	int type;
	int size;
} args_t;

void set_value_list(gpointer data, gpointer user_data)
{
	int len;
	args_t *pargs = (args_t *)user_data;

    if (pargs->size > 0) {
		len = set_value(pargs->ptr, pargs->size, pargs->type, (const char *)data);
		pargs->ptr += len + 1;
		pargs->size -= len + 1;
    }
}

void trace_gconf(const char *fname, int cmd, const char *key, int type, const char *value)
{
	#define BACKTRACE_SIZ 100
	void *array[BACKTRACE_SIZ];
	char **strings = NULL;
	char buf[MAX_PATH];
	msg_t msg;
	size_t size = 0, i;

	sem_wait(&lock);

	if (prt_backtrace) {
		size = backtrace(array, BACKTRACE_SIZ);
		strings = backtrace_symbols_ex(array, size);
	}

	msg.uid = getuid();
	msg.pid = getpid();
	msg.tid = syscall(SYS_gettid);
	time(&msg.timestamp);
	msg.cmd = cmd;
	msg.vtype = type;

	strncpy(msg.procname, get_proc_name(msg.pid, buf), sizeof(msg.procname));
	msg.procname[sizeof(msg.procname) - 1] = '\0';

	if (cmd != GCONF_CMD_UNKNOWN) {
		strncpy(msg.key, key, sizeof(msg.key));
    	msg.key[sizeof(msg.key) - 1] = '\0';
		if (cmd == GCONF_CMD_GET_VALUE || cmd == GCONF_CMD_SET_VALUE) {
			if (value)
				set_value((char *)&msg.value, sizeof(msg.value), type, value);
		} else if (cmd == GCONF_CMD_GET_VALUE_LIST || cmd == GCONF_CMD_SET_VALUE_LIST) {
			args_t args;

			args.ptr = msg.value;
			args.type = type;
			args.size = sizeof(msg.value);
			g_slist_foreach((GSList *)value, set_value_list, &args);
		}
	} else {
		strncpy(msg.key, fname, sizeof(msg.key));
    	msg.key[sizeof(msg.key) - 1] = '\0';
		msg.value[0] = '\0';	
	}
#ifdef LOCAL_LOG
	FILE *fp = NULL;
	if (trace_file_name[0] != '\0')
		fp = fopen(trace_file_name, "at");
	if (fp == NULL) 
		fp = stderr;
	struct tm *tm = localtime(&msg.timestamp);
	fprintf(fp, "%04d-%02d-%02d %d:%d:%d %d \"%s\" %d %x %s %s %d", tm->tm_year + 1900, tm->tm_mon + 1, tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, msg.uid, msg.procname, msg.pid, msg.tid, cmd2str(msg.cmd), msg.key, msg.vtype);
	//fprintf(fp, "(%s)%d %s(%d)", msg.procname, msg.cmd, msg.key, msg.vtype);
	//if (msg.cmd == GCONF_CMD_SET_VALUE || msg.cmd == GCONF_CMD_SET_VALUE_LIST) {
		switch(msg.vtype) {
		case GCONF_VALUE_INT:
			fprintf(fp, " %d\n", *(int *)msg.value);
			break;
		case GCONF_VALUE_BOOL:
			fprintf(fp, " %s\n", *(int *)msg.value? "true" : "false");
			break;
		case GCONF_VALUE_FLOAT:
			fprintf(fp, " %lf\n", *(double *)msg.value);
			break;
		case GCONF_VALUE_STRING:
			fprintf(fp, " %s\n", msg.value);
			break;
		default:
			fprintf(fp, " (UNKNOWN)\n");
			break;
		}
	//} else
	//	fprintf(fp, "\n");
	for (i = 0; i < size; i++)
		fprintf(fp, "\t%p : %s\n", array[i], strings[i]);
	if (fp != stderr)
		fclose(fp);
#else
	send_gconf_msg(msg.cmd, &msg);
#endif
	sem_post(&lock);
}

 GType gconf_client_get_type() {
	static GType (*gconf_client_get_typeORIG)();

	if (!gconf_client_get_typeORIG) {
		gconf_client_get_typeORIG = (GType(*)()) dlsym(RTLD_NEXT, "gconf_client_get_type");
	}
	trace_gconf("gconf_client_get_type", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_get_typeORIG();
}

 GConfClient* gconf_client_get_default() {
	static GConfClient* (*gconf_client_get_defaultORIG)();

	if (!gconf_client_get_defaultORIG) {
		gconf_client_get_defaultORIG = (GConfClient*(*)()) dlsym(RTLD_NEXT, "gconf_client_get_default");
	}
	trace_gconf("gconf_client_get_default", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_get_defaultORIG();
}

 GConfClient* gconf_client_get_for_engine(GConfEngine* engine) {
	static GConfClient* (*gconf_client_get_for_engineORIG)(GConfEngine* engine);

	if (!gconf_client_get_for_engineORIG) {
		gconf_client_get_for_engineORIG = (GConfClient*(*)(GConfEngine* engine)) dlsym(RTLD_NEXT, "gconf_client_get_for_engine");
	}
	trace_gconf("gconf_client_get_for_engine", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_get_for_engineORIG(engine);
}

 void gconf_client_add_dir(GConfClient* client, const gchar* dir, GConfClientPreloadType preload, GError** err) {
	static void (*gconf_client_add_dirORIG)(GConfClient* client, const gchar* dir, GConfClientPreloadType preload, GError** err);

	if (!gconf_client_add_dirORIG) {
		gconf_client_add_dirORIG = (void(*)(GConfClient* client, const gchar* dir, GConfClientPreloadType preload, GError** err)) dlsym(RTLD_NEXT, "gconf_client_add_dir");
	}
	trace_gconf("gconf_client_add_dir", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_add_dirORIG(client, dir, preload, err);
}

 void gconf_client_remove_dir(GConfClient* client, const gchar* dir, GError** err) {
	static void (*gconf_client_remove_dirORIG)(GConfClient* client, const gchar* dir, GError** err);

	if (!gconf_client_remove_dirORIG) {
		gconf_client_remove_dirORIG = (void(*)(GConfClient* client, const gchar* dir, GError** err)) dlsym(RTLD_NEXT, "gconf_client_remove_dir");
	}
	trace_gconf("gconf_client_remove_dir", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_remove_dirORIG(client, dir, err);
}

 guint gconf_client_notify_add(GConfClient* client, const gchar* namespace_section, GConfClientNotifyFunc func, gpointer user_data, GFreeFunc destroy_notify, GError** err) {
	static guint (*gconf_client_notify_addORIG)(GConfClient* client, const gchar* namespace_section, GConfClientNotifyFunc func, gpointer user_data, GFreeFunc destroy_notify, GError** err);

	if (!gconf_client_notify_addORIG) {
		gconf_client_notify_addORIG = (guint(*)(GConfClient* client, const gchar* namespace_section, GConfClientNotifyFunc func, gpointer user_data, GFreeFunc destroy_notify, GError** err)) dlsym(RTLD_NEXT, "gconf_client_notify_add");
	}
	trace_gconf("gconf_client_notify_add", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_notify_addORIG(client, namespace_section, func, user_data, destroy_notify, err);
}

 void gconf_client_notify_remove(GConfClient* client, guint cnxn) {
	static void (*gconf_client_notify_removeORIG)(GConfClient* client, guint cnxn);

	if (!gconf_client_notify_removeORIG) {
		gconf_client_notify_removeORIG = (void(*)(GConfClient* client, guint cnxn)) dlsym(RTLD_NEXT, "gconf_client_notify_remove");
	}
	trace_gconf("gconf_client_notify_remove", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_notify_removeORIG(client, cnxn);
}

 void gconf_client_notify(GConfClient* client, const char* key) {
	static void (*gconf_client_notifyORIG)(GConfClient* client, const char* key);

	if (!gconf_client_notifyORIG) {
		gconf_client_notifyORIG = (void(*)(GConfClient* client, const char* key)) dlsym(RTLD_NEXT, "gconf_client_notify");
	}
	trace_gconf("gconf_client_notify", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_notifyORIG(client, key);
}

 void gconf_client_set_error_handling(GConfClient* client, GConfClientErrorHandlingMode mode) {
	static void (*gconf_client_set_error_handlingORIG)(GConfClient* client, GConfClientErrorHandlingMode mode);

	if (!gconf_client_set_error_handlingORIG) {
		gconf_client_set_error_handlingORIG = (void(*)(GConfClient* client, GConfClientErrorHandlingMode mode)) dlsym(RTLD_NEXT, "gconf_client_set_error_handling");
	}
	trace_gconf("gconf_client_set_error_handling", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_set_error_handlingORIG(client, mode);
}

 void gconf_client_set_global_default_error_handler(GConfClientErrorHandlerFunc func) {
	static void (*gconf_client_set_global_default_error_handlerORIG)(GConfClientErrorHandlerFunc func);

	if (!gconf_client_set_global_default_error_handlerORIG) {
		gconf_client_set_global_default_error_handlerORIG = (void(*)(GConfClientErrorHandlerFunc func)) dlsym(RTLD_NEXT, "gconf_client_set_global_default_error_handler");
	}
	trace_gconf("gconf_client_set_global_default_error_handler", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_set_global_default_error_handlerORIG(func);
}

 void gconf_client_clear_cache(GConfClient* client) {
	static void (*gconf_client_clear_cacheORIG)(GConfClient* client);

	if (!gconf_client_clear_cacheORIG) {
		gconf_client_clear_cacheORIG = (void(*)(GConfClient* client)) dlsym(RTLD_NEXT, "gconf_client_clear_cache");
	}
	trace_gconf("gconf_client_clear_cache", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_clear_cacheORIG(client);
}

 void gconf_client_preload(GConfClient* client, const gchar* dirname, GConfClientPreloadType type, GError** err) {
	static void (*gconf_client_preloadORIG)(GConfClient* client, const gchar* dirname, GConfClientPreloadType type, GError** err);

	if (!gconf_client_preloadORIG) {
		gconf_client_preloadORIG = (void(*)(GConfClient* client, const gchar* dirname, GConfClientPreloadType type, GError** err)) dlsym(RTLD_NEXT, "gconf_client_preload");
	}
	trace_gconf("gconf_client_preload", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_preloadORIG(client, dirname, type, err);
}

 void gconf_client_set(GConfClient* client, const gchar* key, const GConfValue* val, GError** err) {
	static void (*gconf_client_setORIG)(GConfClient* client, const gchar* key, const GConfValue* val, GError** err);
    char buf[VALUE_LEN];

	if (!gconf_client_setORIG) {
		gconf_client_setORIG = (void(*)(GConfClient* client, const gchar* key, const GConfValue* val, GError** err)) dlsym(RTLD_NEXT, "gconf_client_set");
	}
	get_gconfvalue(val, buf, sizeof(buf));
	trace_gconf("gconf_client_set", GCONF_CMD_SET_VALUE, key, val->type, (const char *)buf);
	return gconf_client_setORIG(client, key, val, err);
}

 GConfValue* gconf_client_get(GConfClient* client, const gchar* key, GError** err) {
	static GConfValue* (*gconf_client_getORIG)(GConfClient* client, const gchar* key, GError** err);
	GConfValue *ret = NULL;
	char buf[VALUE_LEN];
	int type = GCONF_VALUE_INVALID;

	if (!gconf_client_getORIG) {
		gconf_client_getORIG = (GConfValue*(*)(GConfClient* client, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_client_get");
	}
	ret = gconf_client_getORIG(client, key, err);
	if (ret) {
		get_gconfvalue(ret, buf, sizeof(buf));
		type = ret->type;
	}
	trace_gconf("gconf_client_get", GCONF_CMD_GET_VALUE, key, type, buf);
	return ret;
}

 GConfValue* gconf_client_get_without_default(GConfClient* client, const gchar* key, GError** err) {
	static GConfValue* (*gconf_client_get_without_defaultORIG)(GConfClient* client, const gchar* key, GError** err);

	if (!gconf_client_get_without_defaultORIG) {
		gconf_client_get_without_defaultORIG = (GConfValue*(*)(GConfClient* client, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_client_get_without_default");
	}
	trace_gconf("gconf_client_get_without_default", GCONF_CMD_GET_VALUE, key, GCONF_VALUE_INVALID, NULL);
	return gconf_client_get_without_defaultORIG(client, key, err);
}

 GConfEntry* gconf_client_get_entry(GConfClient* client, const gchar* key, const gchar* locale, gboolean use_schema_default, GError** err) {
	static GConfEntry* (*gconf_client_get_entryORIG)(GConfClient* client, const gchar* key, const gchar* locale, gboolean use_schema_default, GError** err);
	GConfEntry *ret = NULL;
	GConfValue *val = NULL;
	int type = GCONF_VALUE_INVALID;
	char buf[VALUE_LEN];

	if (!gconf_client_get_entryORIG) {
		gconf_client_get_entryORIG = (GConfEntry*(*)(GConfClient* client, const gchar* key, const gchar* locale, gboolean use_schema_default, GError** err)) dlsym(RTLD_NEXT, "gconf_client_get_entry");
	}
	ret = gconf_client_get_entryORIG(client, key, locale, use_schema_default, err);
	if (ret) {
		val = gconf_entry_get_value(ret);
		if (val) {
			get_gconfvalue(val, buf, sizeof(buf));
			type = val->type;
		}
	}
	trace_gconf("gconf_client_get_entry", GCONF_CMD_GET_VALUE, key, type, buf);
	return ret;
}

 GConfValue* gconf_client_get_default_from_schema(GConfClient* client, const gchar* key, GError** err) {
	static GConfValue* (*gconf_client_get_default_from_schemaORIG)(GConfClient* client, const gchar* key, GError** err);

	if (!gconf_client_get_default_from_schemaORIG) {
		gconf_client_get_default_from_schemaORIG = (GConfValue*(*)(GConfClient* client, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_client_get_default_from_schema");
	}
	trace_gconf("gconf_client_get_default_from_schema", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_get_default_from_schemaORIG(client, key, err);
}

 gboolean gconf_client_unset(GConfClient* client, const gchar* key, GError** err) {
	static gboolean (*gconf_client_unsetORIG)(GConfClient* client, const gchar* key, GError** err);

	if (!gconf_client_unsetORIG) {
		gconf_client_unsetORIG = (gboolean(*)(GConfClient* client, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_client_unset");
	}
	trace_gconf("gconf_client_unset", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_unsetORIG(client, key, err);
}

 gboolean gconf_client_recursive_unset(GConfClient* client, const char* key, GConfUnsetFlags flags, GError** err) {
	static gboolean (*gconf_client_recursive_unsetORIG)(GConfClient* client, const char* key, GConfUnsetFlags flags, GError** err);

	if (!gconf_client_recursive_unsetORIG) {
		gconf_client_recursive_unsetORIG = (gboolean(*)(GConfClient* client, const char* key, GConfUnsetFlags flags, GError** err)) dlsym(RTLD_NEXT, "gconf_client_recursive_unset");
	}
	trace_gconf("gconf_client_recursive_unset", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_recursive_unsetORIG(client, key, flags, err);
}

 GSList* gconf_client_all_entries(GConfClient* client, const gchar* dir, GError** err) {
	static GSList* (*gconf_client_all_entriesORIG)(GConfClient* client, const gchar* dir, GError** err);

	if (!gconf_client_all_entriesORIG) {
		gconf_client_all_entriesORIG = (GSList*(*)(GConfClient* client, const gchar* dir, GError** err)) dlsym(RTLD_NEXT, "gconf_client_all_entries");
	}
	trace_gconf("gconf_client_all_entries", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_all_entriesORIG(client, dir, err);
}

 GSList* gconf_client_all_dirs(GConfClient* client, const gchar* dir, GError** err) {
	static GSList* (*gconf_client_all_dirsORIG)(GConfClient* client, const gchar* dir, GError** err);

	if (!gconf_client_all_dirsORIG) {
		gconf_client_all_dirsORIG = (GSList*(*)(GConfClient* client, const gchar* dir, GError** err)) dlsym(RTLD_NEXT, "gconf_client_all_dirs");
	}
	trace_gconf("gconf_client_all_dirs", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_all_dirsORIG(client, dir, err);
}

 void gconf_client_suggest_sync(GConfClient* client, GError** err) {
	static void (*gconf_client_suggest_syncORIG)(GConfClient* client, GError** err);

	if (!gconf_client_suggest_syncORIG) {
		gconf_client_suggest_syncORIG = (void(*)(GConfClient* client, GError** err)) dlsym(RTLD_NEXT, "gconf_client_suggest_sync");
	}
	trace_gconf("gconf_client_suggest_sync", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_suggest_syncORIG(client, err);
}

 gboolean gconf_client_dir_exists(GConfClient* client, const gchar* dir, GError** err) {
	static gboolean (*gconf_client_dir_existsORIG)(GConfClient* client, const gchar* dir, GError** err);

	if (!gconf_client_dir_existsORIG) {
		gconf_client_dir_existsORIG = (gboolean(*)(GConfClient* client, const gchar* dir, GError** err)) dlsym(RTLD_NEXT, "gconf_client_dir_exists");
	}
	trace_gconf("gconf_client_dir_exists", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_dir_existsORIG(client, dir, err);
}

 gboolean gconf_client_key_is_writable(GConfClient* client, const gchar* key, GError** err) {
	static gboolean (*gconf_client_key_is_writableORIG)(GConfClient* client, const gchar* key, GError** err);
	gboolean value;

	if (!gconf_client_key_is_writableORIG) {
		gconf_client_key_is_writableORIG = (gboolean(*)(GConfClient* client, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_client_key_is_writable");
	}
	trace_gconf("gconf_client_key_is_writable", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_key_is_writableORIG(client, key, err);
}

 gdouble gconf_client_get_float(GConfClient* client, const gchar* key, GError** err) {
	static gdouble (*gconf_client_get_floatORIG)(GConfClient* client, const gchar* key, GError** err);
	gdouble value;

	if (!gconf_client_get_floatORIG) {
		gconf_client_get_floatORIG = (gdouble(*)(GConfClient* client, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_client_get_float");
	}
	value = gconf_client_get_floatORIG(client, key, err);
	trace_gconf("gconf_client_get_float", GCONF_CMD_GET_VALUE, key, GCONF_VALUE_FLOAT, &value);
	return value;
}

 gint gconf_client_get_int(GConfClient* client, const gchar* key, GError** err) {
	static gint (*gconf_client_get_intORIG)(GConfClient* client, const gchar* key, GError** err);
	gint value;

	if (!gconf_client_get_intORIG) {
		gconf_client_get_intORIG = (gint(*)(GConfClient* client, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_client_get_int");
	}
	value = gconf_client_get_intORIG(client, key, err);
	trace_gconf("gconf_client_get_int", GCONF_CMD_GET_VALUE, key, GCONF_VALUE_INT, &value);
	return value;
}

 gchar* gconf_client_get_string(GConfClient* client, const gchar* key, GError** err) {
	static gchar* (*gconf_client_get_stringORIG)(GConfClient* client, const gchar* key, GError** err);
	gchar *value;

	if (!gconf_client_get_stringORIG) {
		gconf_client_get_stringORIG = (gchar*(*)(GConfClient* client, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_client_get_string");
	}
	value = gconf_client_get_stringORIG(client, key, err);
	trace_gconf("gconf_client_get_string", GCONF_CMD_GET_VALUE, key, GCONF_VALUE_STRING, value);
	return value;
}

 gboolean gconf_client_get_bool(GConfClient* client, const gchar* key, GError** err) {
	static gboolean (*gconf_client_get_boolORIG)(GConfClient* client, const gchar* key, GError** err);
	gboolean value;

	if (!gconf_client_get_boolORIG) {
		gconf_client_get_boolORIG = (gboolean(*)(GConfClient* client, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_client_get_bool");
	}
	value = gconf_client_get_boolORIG(client, key, err);
	trace_gconf("gconf_client_get_bool", GCONF_CMD_GET_VALUE, key, GCONF_VALUE_BOOL, &value);
	return value;
}

 GConfSchema* gconf_client_get_schema(GConfClient* client, const gchar* key, GError** err) {
	static GConfSchema* (*gconf_client_get_schemaORIG)(GConfClient* client, const gchar* key, GError** err);

	if (!gconf_client_get_schemaORIG) {
		gconf_client_get_schemaORIG = (GConfSchema*(*)(GConfClient* client, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_client_get_schema");
	}
	trace_gconf("gconf_client_get_schema", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_get_schemaORIG(client, key, err);
}

 GSList* gconf_client_get_list(GConfClient* client, const gchar* key, GConfValueType list_type, GError** err) {
	static GSList* (*gconf_client_get_listORIG)(GConfClient* client, const gchar* key, GConfValueType list_type, GError** err);
	GSList *list;

	if (!gconf_client_get_listORIG) {
		gconf_client_get_listORIG = (GSList*(*)(GConfClient* client, const gchar* key, GConfValueType list_type, GError** err)) dlsym(RTLD_NEXT, "gconf_client_get_list");
	}
	list = gconf_client_get_listORIG(client, key, list_type, err);
	trace_gconf("gconf_client_get_list", GCONF_CMD_GET_VALUE_LIST, key, list_type, list);
	return list;
}

 gboolean gconf_client_get_pair(GConfClient* client, const gchar* key, GConfValueType car_type, GConfValueType cdr_type, gpointer car_retloc, gpointer cdr_retloc, GError** err) {
	static gboolean (*gconf_client_get_pairORIG)(GConfClient* client, const gchar* key, GConfValueType car_type, GConfValueType cdr_type, gpointer car_retloc, gpointer cdr_retloc, GError** err);

	if (!gconf_client_get_pairORIG) {
		gconf_client_get_pairORIG = (gboolean(*)(GConfClient* client, const gchar* key, GConfValueType car_type, GConfValueType cdr_type, gpointer car_retloc, gpointer cdr_retloc, GError** err)) dlsym(RTLD_NEXT, "gconf_client_get_pair");
	}
	trace_gconf("gconf_client_get_pair", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_get_pairORIG(client, key, car_type, cdr_type, car_retloc, cdr_retloc, err);
}

 gboolean gconf_client_set_float(GConfClient* client, const gchar* key, gdouble val, GError** err) {
	static gboolean (*gconf_client_set_floatORIG)(GConfClient* client, const gchar* key, gdouble val, GError** err);

	if (!gconf_client_set_floatORIG) {
		gconf_client_set_floatORIG = (gboolean(*)(GConfClient* client, const gchar* key, gdouble val, GError** err)) dlsym(RTLD_NEXT, "gconf_client_set_float");
	}
	trace_gconf("gconf_client_set_float", GCONF_CMD_SET_VALUE, key, GCONF_VALUE_FLOAT, (const char *)&val);
	return gconf_client_set_floatORIG(client, key, val, err);
}

 gboolean gconf_client_set_int(GConfClient* client, const gchar* key, gint val, GError** err) {
	static gboolean (*gconf_client_set_intORIG)(GConfClient* client, const gchar* key, gint val, GError** err);

	if (!gconf_client_set_intORIG) {
		gconf_client_set_intORIG = (gboolean(*)(GConfClient* client, const gchar* key, gint val, GError** err)) dlsym(RTLD_NEXT, "gconf_client_set_int");
	}
	trace_gconf("gconf_client_set_int", GCONF_CMD_SET_VALUE, key, GCONF_VALUE_INT, (const char *)&val);
	return gconf_client_set_intORIG(client, key, val, err);
}

 gboolean gconf_client_set_string(GConfClient* client, const gchar* key, const gchar* val, GError** err) {
	static gboolean (*gconf_client_set_stringORIG)(GConfClient* client, const gchar* key, const gchar* val, GError** err);

	if (!gconf_client_set_stringORIG) {
		gconf_client_set_stringORIG = (gboolean(*)(GConfClient* client, const gchar* key, const gchar* val, GError** err)) dlsym(RTLD_NEXT, "gconf_client_set_string");
	}
	trace_gconf("gconf_client_set_string", GCONF_CMD_SET_VALUE, key, GCONF_VALUE_STRING, (const char *)val);
	return gconf_client_set_stringORIG(client, key, val, err);
}

 gboolean gconf_client_set_bool(GConfClient* client, const gchar* key, gboolean val, GError** err) {
	static gboolean (*gconf_client_set_boolORIG)(GConfClient* client, const gchar* key, gboolean val, GError** err);

	if (!gconf_client_set_boolORIG) {
		gconf_client_set_boolORIG = (gboolean(*)(GConfClient* client, const gchar* key, gboolean val, GError** err)) dlsym(RTLD_NEXT, "gconf_client_set_bool");
	}
	trace_gconf("gconf_client_set_bool", GCONF_CMD_SET_VALUE, key, GCONF_VALUE_BOOL, (const char *)&val);
	return gconf_client_set_boolORIG(client, key, val, err);
}

 gboolean gconf_client_set_schema(GConfClient* client, const gchar* key, const GConfSchema* val, GError** err) {
	static gboolean (*gconf_client_set_schemaORIG)(GConfClient* client, const gchar* key, const GConfSchema* val, GError** err);

	if (!gconf_client_set_schemaORIG) {
		gconf_client_set_schemaORIG = (gboolean(*)(GConfClient* client, const gchar* key, const GConfSchema* val, GError** err)) dlsym(RTLD_NEXT, "gconf_client_set_schema");
	}
	trace_gconf("gconf_client_set_schema", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_set_schemaORIG(client, key, val, err);
}

 gboolean gconf_client_set_list(GConfClient* client, const gchar* key, GConfValueType list_type, GSList* list, GError** err) {
	static gboolean (*gconf_client_set_listORIG)(GConfClient* client, const gchar* key, GConfValueType list_type, GSList* list, GError** err);

	if (!gconf_client_set_listORIG) {
		gconf_client_set_listORIG = (gboolean(*)(GConfClient* client, const gchar* key, GConfValueType list_type, GSList* list, GError** err)) dlsym(RTLD_NEXT, "gconf_client_set_list");
	}
	trace_gconf("gconf_client_set_list", GCONF_CMD_SET_VALUE_LIST, key, list_type, (const char *)list);
	return gconf_client_set_listORIG(client, key, list_type, list, err);
}

 gboolean gconf_client_set_pair(GConfClient* client, const gchar* key, GConfValueType car_type, GConfValueType cdr_type, gconstpointer address_of_car, gconstpointer address_of_cdr, GError** err) {
	static gboolean (*gconf_client_set_pairORIG)(GConfClient* client, const gchar* key, GConfValueType car_type, GConfValueType cdr_type, gconstpointer address_of_car, gconstpointer address_of_cdr, GError** err);

	if (!gconf_client_set_pairORIG) {
		gconf_client_set_pairORIG = (gboolean(*)(GConfClient* client, const gchar* key, GConfValueType car_type, GConfValueType cdr_type, gconstpointer address_of_car, gconstpointer address_of_cdr, GError** err)) dlsym(RTLD_NEXT, "gconf_client_set_pair");
	}
	trace_gconf("gconf_client_set_pair", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_set_pairORIG(client, key, car_type, cdr_type, address_of_car, address_of_cdr, err);
}

 void gconf_client_error(GConfClient* client, GError* error) {
	static void (*gconf_client_errorORIG)(GConfClient* client, GError* error);

	if (!gconf_client_errorORIG) {
		gconf_client_errorORIG = (void(*)(GConfClient* client, GError* error)) dlsym(RTLD_NEXT, "gconf_client_error");
	}
	trace_gconf("gconf_client_error", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_errorORIG(client, error);
}

 void gconf_client_unreturned_error(GConfClient* client, GError* error) {
	static void (*gconf_client_unreturned_errorORIG)(GConfClient* client, GError* error);

	if (!gconf_client_unreturned_errorORIG) {
		gconf_client_unreturned_errorORIG = (void(*)(GConfClient* client, GError* error)) dlsym(RTLD_NEXT, "gconf_client_unreturned_error");
	}
	trace_gconf("gconf_client_unreturned_error", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_unreturned_errorORIG(client, error);
}

 void gconf_client_value_changed(GConfClient* client, const gchar* key, GConfValue* value) {
	static void (*gconf_client_value_changedORIG)(GConfClient* client, const gchar* key, GConfValue* value);

	if (!gconf_client_value_changedORIG) {
		gconf_client_value_changedORIG = (void(*)(GConfClient* client, const gchar* key, GConfValue* value)) dlsym(RTLD_NEXT, "gconf_client_value_changed");
	}
	trace_gconf("gconf_client_value_changed", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_value_changedORIG(client, key, value);
}

 gboolean gconf_client_commit_change_set(GConfClient* client, GConfChangeSet* cs, gboolean remove_committed, GError** err) {
	static gboolean (*gconf_client_commit_change_setORIG)(GConfClient* client, GConfChangeSet* cs, gboolean remove_committed, GError** err);

	if (!gconf_client_commit_change_setORIG) {
		gconf_client_commit_change_setORIG = (gboolean(*)(GConfClient* client, GConfChangeSet* cs, gboolean remove_committed, GError** err)) dlsym(RTLD_NEXT, "gconf_client_commit_change_set");
	}
	trace_gconf("gconf_client_commit_change_set", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_commit_change_setORIG(client, cs, remove_committed, err);
}

 GConfChangeSet* gconf_client_reverse_change_set(GConfClient* client, GConfChangeSet* cs, GError** err) {
	static GConfChangeSet* (*gconf_client_reverse_change_setORIG)(GConfClient* client, GConfChangeSet* cs, GError** err);

	if (!gconf_client_reverse_change_setORIG) {
		gconf_client_reverse_change_setORIG = (GConfChangeSet*(*)(GConfClient* client, GConfChangeSet* cs, GError** err)) dlsym(RTLD_NEXT, "gconf_client_reverse_change_set");
	}
	trace_gconf("gconf_client_reverse_change_set", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_reverse_change_setORIG(client, cs, err);
}

 GConfChangeSet* gconf_client_change_set_from_currentv(GConfClient* client, const gchar** keys, GError** err) {
	static GConfChangeSet* (*gconf_client_change_set_from_currentvORIG)(GConfClient* client, const gchar** keys, GError** err);

	if (!gconf_client_change_set_from_currentvORIG) {
		gconf_client_change_set_from_currentvORIG = (GConfChangeSet*(*)(GConfClient* client, const gchar** keys, GError** err)) dlsym(RTLD_NEXT, "gconf_client_change_set_from_currentv");
	}
	trace_gconf("gconf_client_change_set_from_currentv", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_client_change_set_from_currentvORIG(client, keys, err);
}

 guint gconf_engine_notify_add(GConfEngine* conf, const gchar* namespace_section, GConfNotifyFunc func, gpointer user_data, GError** err) {
	static guint (*gconf_engine_notify_addORIG)(GConfEngine* conf, const gchar* namespace_section, GConfNotifyFunc func, gpointer user_data, GError** err);

	if (!gconf_engine_notify_addORIG) {
		gconf_engine_notify_addORIG = (guint(*)(GConfEngine* conf, const gchar* namespace_section, GConfNotifyFunc func, gpointer user_data, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_notify_add");
	}
	trace_gconf("gconf_engine_notify_add", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_notify_addORIG(conf, namespace_section, func, user_data, err);
}

 void gconf_engine_notify_remove(GConfEngine* conf, guint cnxn) {
	static void (*gconf_engine_notify_removeORIG)(GConfEngine* conf, guint cnxn);

	if (!gconf_engine_notify_removeORIG) {
		gconf_engine_notify_removeORIG = (void(*)(GConfEngine* conf, guint cnxn)) dlsym(RTLD_NEXT, "gconf_engine_notify_remove");
	}
	trace_gconf("gconf_engine_notify_remove", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_notify_removeORIG(conf, cnxn);
}

 GConfValue* gconf_engine_get(GConfEngine* conf, const gchar* key, GError** err) {
	static GConfValue* (*gconf_engine_getORIG)(GConfEngine* conf, const gchar* key, GError** err);

	if (!gconf_engine_getORIG) {
		gconf_engine_getORIG = (GConfValue*(*)(GConfEngine* conf, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get");
	}
	trace_gconf("gconf_engine_get", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_getORIG(conf, key, err);
}

 GConfValue* gconf_engine_get_without_default(GConfEngine* conf, const gchar* key, GError** err) {
	static GConfValue* (*gconf_engine_get_without_defaultORIG)(GConfEngine* conf, const gchar* key, GError** err);

	if (!gconf_engine_get_without_defaultORIG) {
		gconf_engine_get_without_defaultORIG = (GConfValue*(*)(GConfEngine* conf, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_without_default");
	}
	trace_gconf("gconf_engine_get_without_default", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_without_defaultORIG(conf, key, err);
}

 GConfEntry* gconf_engine_get_entry(GConfEngine* conf, const gchar* key, const gchar* locale, gboolean use_schema_default, GError** err) {
	static GConfEntry* (*gconf_engine_get_entryORIG)(GConfEngine* conf, const gchar* key, const gchar* locale, gboolean use_schema_default, GError** err);

	if (!gconf_engine_get_entryORIG) {
		gconf_engine_get_entryORIG = (GConfEntry*(*)(GConfEngine* conf, const gchar* key, const gchar* locale, gboolean use_schema_default, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_entry");
	}
	trace_gconf("gconf_engine_get_entry", GCONF_CMD_GET_VALUE, key, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_entryORIG(conf, key, locale, use_schema_default, err);
}

 GConfValue* gconf_engine_get_with_locale(GConfEngine* conf, const gchar* key, const gchar* locale, GError** err) {
	static GConfValue* (*gconf_engine_get_with_localeORIG)(GConfEngine* conf, const gchar* key, const gchar* locale, GError** err);

	if (!gconf_engine_get_with_localeORIG) {
		gconf_engine_get_with_localeORIG = (GConfValue*(*)(GConfEngine* conf, const gchar* key, const gchar* locale, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_with_locale");
	}
	trace_gconf("gconf_engine_get_with_locale", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_with_localeORIG(conf, key, locale, err);
}

 GConfValue* gconf_engine_get_default_from_schema(GConfEngine* conf, const gchar* key, GError** err) {
	static GConfValue* (*gconf_engine_get_default_from_schemaORIG)(GConfEngine* conf, const gchar* key, GError** err);

	if (!gconf_engine_get_default_from_schemaORIG) {
		gconf_engine_get_default_from_schemaORIG = (GConfValue*(*)(GConfEngine* conf, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_default_from_schema");
	}
	trace_gconf("gconf_engine_get_default_from_schema", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_default_from_schemaORIG(conf, key, err);
}

 gboolean gconf_engine_set(GConfEngine* conf, const gchar* key, const GConfValue* value, GError** err) {
	static gboolean (*gconf_engine_setORIG)(GConfEngine* conf, const gchar* key, const GConfValue* value, GError** err);
    char buf[VALUE_LEN];
const char *str = NULL;

	if (!gconf_engine_setORIG) {
		gconf_engine_setORIG = (gboolean(*)(GConfEngine* conf, const gchar* key, const GConfValue* value, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_set");
	}
	get_gconfvalue(value, buf, sizeof(buf));
	trace_gconf("gconf_engine_set", GCONF_CMD_SET_VALUE, key, value->type, (const char *)buf);
	return gconf_engine_setORIG(conf, key, value, err);
}

 gboolean gconf_engine_unset(GConfEngine* conf, const gchar* key, GError** err) {
	static gboolean (*gconf_engine_unsetORIG)(GConfEngine* conf, const gchar* key, GError** err);

	if (!gconf_engine_unsetORIG) {
		gconf_engine_unsetORIG = (gboolean(*)(GConfEngine* conf, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_unset");
	}
	trace_gconf("gconf_engine_unset", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_unsetORIG(conf, key, err);
}

 gboolean gconf_engine_associate_schema(GConfEngine* conf, const gchar* key, const gchar* schema_key, GError** err) {
	static gboolean (*gconf_engine_associate_schemaORIG)(GConfEngine* conf, const gchar* key, const gchar* schema_key, GError** err);

	if (!gconf_engine_associate_schemaORIG) {
		gconf_engine_associate_schemaORIG = (gboolean(*)(GConfEngine* conf, const gchar* key, const gchar* schema_key, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_associate_schema");
	}
	trace_gconf("gconf_engine_associate_schema", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_associate_schemaORIG(conf, key, schema_key, err);
}

 GSList* gconf_engine_all_entries(GConfEngine* conf, const gchar* dir, GError** err) {
	static GSList* (*gconf_engine_all_entriesORIG)(GConfEngine* conf, const gchar* dir, GError** err);

	if (!gconf_engine_all_entriesORIG) {
		gconf_engine_all_entriesORIG = (GSList*(*)(GConfEngine* conf, const gchar* dir, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_all_entries");
	}
	trace_gconf("gconf_engine_all_entries", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_all_entriesORIG(conf, dir, err);
}

 GSList* gconf_engine_all_dirs(GConfEngine* conf, const gchar* dir, GError** err) {
	static GSList* (*gconf_engine_all_dirsORIG)(GConfEngine* conf, const gchar* dir, GError** err);

	if (!gconf_engine_all_dirsORIG) {
		gconf_engine_all_dirsORIG = (GSList*(*)(GConfEngine* conf, const gchar* dir, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_all_dirs");
	}
	trace_gconf("gconf_engine_all_dirs", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_all_dirsORIG(conf, dir, err);
}

 void gconf_engine_suggest_sync(GConfEngine* conf, GError** err) {
	static void (*gconf_engine_suggest_syncORIG)(GConfEngine* conf, GError** err);

	if (!gconf_engine_suggest_syncORIG) {
		gconf_engine_suggest_syncORIG = (void(*)(GConfEngine* conf, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_suggest_sync");
	}
	trace_gconf("gconf_engine_suggest_sync", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_suggest_syncORIG(conf, err);
}

 gboolean gconf_engine_dir_exists(GConfEngine* conf, const gchar* dir, GError** err) {
	static gboolean (*gconf_engine_dir_existsORIG)(GConfEngine* conf, const gchar* dir, GError** err);

	if (!gconf_engine_dir_existsORIG) {
		gconf_engine_dir_existsORIG = (gboolean(*)(GConfEngine* conf, const gchar* dir, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_dir_exists");
	}
	trace_gconf("gconf_engine_dir_exists", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_dir_existsORIG(conf, dir, err);
}

 void gconf_engine_remove_dir(GConfEngine* conf, const gchar* dir, GError** err) {
	static void (*gconf_engine_remove_dirORIG)(GConfEngine* conf, const gchar* dir, GError** err);

	if (!gconf_engine_remove_dirORIG) {
		gconf_engine_remove_dirORIG = (void(*)(GConfEngine* conf, const gchar* dir, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_remove_dir");
	}
	trace_gconf("gconf_engine_remove_dir", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_remove_dirORIG(conf, dir, err);
}

 gboolean gconf_engine_key_is_writable(GConfEngine* conf, const gchar* key, GError** err) {
	static gboolean (*gconf_engine_key_is_writableORIG)(GConfEngine* conf, const gchar* key, GError** err);

	if (!gconf_engine_key_is_writableORIG) {
		gconf_engine_key_is_writableORIG = (gboolean(*)(GConfEngine* conf, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_key_is_writable");
	}
	trace_gconf("gconf_engine_key_is_writable", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_key_is_writableORIG(conf, key, err);
}

 gboolean gconf_valid_key(const gchar* key, gchar** why_invalid) {
	static gboolean (*gconf_valid_keyORIG)(const gchar* key, gchar** why_invalid);

	if (!gconf_valid_keyORIG) {
		gconf_valid_keyORIG = (gboolean(*)(const gchar* key, gchar** why_invalid)) dlsym(RTLD_NEXT, "gconf_valid_key");
	}
	trace_gconf("gconf_valid_key", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_valid_keyORIG(key, why_invalid);
}

 gboolean gconf_key_is_below(const gchar* above, const gchar* below) {
	static gboolean (*gconf_key_is_belowORIG)(const gchar* above, const gchar* below);

	if (!gconf_key_is_belowORIG) {
		gconf_key_is_belowORIG = (gboolean(*)(const gchar* above, const gchar* below)) dlsym(RTLD_NEXT, "gconf_key_is_below");
	}
	trace_gconf("gconf_key_is_below", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_key_is_belowORIG(above, below);
}

 gchar* gconf_concat_dir_and_key(const gchar* dir, const gchar* key) {
	static gchar* (*gconf_concat_dir_and_keyORIG)(const gchar* dir, const gchar* key);

	if (!gconf_concat_dir_and_keyORIG) {
		gconf_concat_dir_and_keyORIG = (gchar*(*)(const gchar* dir, const gchar* key)) dlsym(RTLD_NEXT, "gconf_concat_dir_and_key");
	}
	trace_gconf("gconf_concat_dir_and_key", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_concat_dir_and_keyORIG(dir, key);
}

 gchar* gconf_unique_key() {
	static gchar* (*gconf_unique_keyORIG)();

	if (!gconf_unique_keyORIG) {
		gconf_unique_keyORIG = (gchar*(*)()) dlsym(RTLD_NEXT, "gconf_unique_key");
	}
	trace_gconf("gconf_unique_key", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_unique_keyORIG();
}

 char* gconf_escape_key(const char* arbitrary_text, int len) {
	static char* (*gconf_escape_keyORIG)(const char* arbitrary_text, int len);

	if (!gconf_escape_keyORIG) {
		gconf_escape_keyORIG = (char*(*)(const char* arbitrary_text, int len)) dlsym(RTLD_NEXT, "gconf_escape_key");
	}
	trace_gconf("gconf_escape_key", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_escape_keyORIG(arbitrary_text, len);
}

 char* gconf_unescape_key(const char* escaped_key, int len) {
	static char* (*gconf_unescape_keyORIG)(const char* escaped_key, int len);

	if (!gconf_unescape_keyORIG) {
		gconf_unescape_keyORIG = (char*(*)(const char* escaped_key, int len)) dlsym(RTLD_NEXT, "gconf_unescape_key");
	}
	trace_gconf("gconf_unescape_key", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_unescape_keyORIG(escaped_key, len);
}

 gdouble gconf_engine_get_float(GConfEngine* conf, const gchar* key, GError** err) {
	static gdouble (*gconf_engine_get_floatORIG)(GConfEngine* conf, const gchar* key, GError** err);

	if (!gconf_engine_get_floatORIG) {
		gconf_engine_get_floatORIG = (gdouble(*)(GConfEngine* conf, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_float");
	}
	trace_gconf("gconf_engine_get_float", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_floatORIG(conf, key, err);
}

 gint gconf_engine_get_int(GConfEngine* conf, const gchar* key, GError** err) {
	static gint (*gconf_engine_get_intORIG)(GConfEngine* conf, const gchar* key, GError** err);

	if (!gconf_engine_get_intORIG) {
		gconf_engine_get_intORIG = (gint(*)(GConfEngine* conf, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_int");
	}
	trace_gconf("gconf_engine_get_int", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_intORIG(conf, key, err);
}

 gchar* gconf_engine_get_string(GConfEngine* conf, const gchar* key, GError** err) {
	static gchar* (*gconf_engine_get_stringORIG)(GConfEngine* conf, const gchar* key, GError** err);

	if (!gconf_engine_get_stringORIG) {
		gconf_engine_get_stringORIG = (gchar*(*)(GConfEngine* conf, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_string");
	}
	trace_gconf("gconf_engine_get_string", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_stringORIG(conf, key, err);
}

 gboolean gconf_engine_get_bool(GConfEngine* conf, const gchar* key, GError** err) {
	static gboolean (*gconf_engine_get_boolORIG)(GConfEngine* conf, const gchar* key, GError** err);

	if (!gconf_engine_get_boolORIG) {
		gconf_engine_get_boolORIG = (gboolean(*)(GConfEngine* conf, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_bool");
	}
	trace_gconf("gconf_engine_get_bool", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_boolORIG(conf, key, err);
}

 GConfSchema* gconf_engine_get_schema(GConfEngine* conf, const gchar* key, GError** err) {
	static GConfSchema* (*gconf_engine_get_schemaORIG)(GConfEngine* conf, const gchar* key, GError** err);

	if (!gconf_engine_get_schemaORIG) {
		gconf_engine_get_schemaORIG = (GConfSchema*(*)(GConfEngine* conf, const gchar* key, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_schema");
	}
	trace_gconf("gconf_engine_get_schema", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_schemaORIG(conf, key, err);
}

 GSList* gconf_engine_get_list(GConfEngine* conf, const gchar* key, GConfValueType list_type, GError** err) {
	static GSList* (*gconf_engine_get_listORIG)(GConfEngine* conf, const gchar* key, GConfValueType list_type, GError** err);
	GSList *list;

	if (!gconf_engine_get_listORIG) {
		gconf_engine_get_listORIG = (GSList*(*)(GConfEngine* conf, const gchar* key, GConfValueType list_type, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_list");
	}
	list = gconf_engine_get_listORIG(conf, key, list_type, err);
	trace_gconf("gconf_engine_get_list", GCONF_CMD_UNKNOWN, NULL, list_type, list);
	return list;
}

 gboolean gconf_engine_get_pair(GConfEngine* conf, const gchar* key, GConfValueType car_type, GConfValueType cdr_type, gpointer car_retloc, gpointer cdr_retloc, GError** err) {
	static gboolean (*gconf_engine_get_pairORIG)(GConfEngine* conf, const gchar* key, GConfValueType car_type, GConfValueType cdr_type, gpointer car_retloc, gpointer cdr_retloc, GError** err);

	if (!gconf_engine_get_pairORIG) {
		gconf_engine_get_pairORIG = (gboolean(*)(GConfEngine* conf, const gchar* key, GConfValueType car_type, GConfValueType cdr_type, gpointer car_retloc, gpointer cdr_retloc, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_pair");
	}
	trace_gconf("gconf_engine_get_pair", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_pairORIG(conf, key, car_type, cdr_type, car_retloc, cdr_retloc, err);
}

 gboolean gconf_engine_set_float(GConfEngine* conf, const gchar* key, gdouble val, GError** err) {
	static gboolean (*gconf_engine_set_floatORIG)(GConfEngine* conf, const gchar* key, gdouble val, GError** err);

	if (!gconf_engine_set_floatORIG) {
		gconf_engine_set_floatORIG = (gboolean(*)(GConfEngine* conf, const gchar* key, gdouble val, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_set_float");
	}
	trace_gconf("gconf_engine_set_float", GCONF_CMD_SET_VALUE, key, GCONF_VALUE_FLOAT, (const char *)&val);
	return gconf_engine_set_floatORIG(conf, key, val, err);
}

 gboolean gconf_engine_set_int(GConfEngine* conf, const gchar* key, gint val, GError** err) {
	static gboolean (*gconf_engine_set_intORIG)(GConfEngine* conf, const gchar* key, gint val, GError** err);

	if (!gconf_engine_set_intORIG) {
		gconf_engine_set_intORIG = (gboolean(*)(GConfEngine* conf, const gchar* key, gint val, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_set_int");
	}
	trace_gconf("gconf_engine_set_int", GCONF_CMD_SET_VALUE, key, GCONF_VALUE_INT, (const char *)&val);
	return gconf_engine_set_intORIG(conf, key, val, err);
}

 gboolean gconf_engine_set_string(GConfEngine* conf, const gchar* key, const gchar* val, GError** err) {
	static gboolean (*gconf_engine_set_stringORIG)(GConfEngine* conf, const gchar* key, const gchar* val, GError** err);

	if (!gconf_engine_set_stringORIG) {
		gconf_engine_set_stringORIG = (gboolean(*)(GConfEngine* conf, const gchar* key, const gchar* val, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_set_string");
	}
	trace_gconf("gconf_engine_set_string", GCONF_CMD_SET_VALUE, key, GCONF_VALUE_STRING, val);
	return gconf_engine_set_stringORIG(conf, key, val, err);
}

 gboolean gconf_engine_set_bool(GConfEngine* conf, const gchar* key, gboolean val, GError** err) {
	static gboolean (*gconf_engine_set_boolORIG)(GConfEngine* conf, const gchar* key, gboolean val, GError** err);

	if (!gconf_engine_set_boolORIG) {
		gconf_engine_set_boolORIG = (gboolean(*)(GConfEngine* conf, const gchar* key, gboolean val, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_set_bool");
	}
	trace_gconf("gconf_engine_set_bool", GCONF_CMD_SET_VALUE, key, GCONF_VALUE_BOOL, (const char *)&val);
	return gconf_engine_set_boolORIG(conf, key, val, err);
}

 gboolean gconf_engine_set_schema(GConfEngine* conf, const gchar* key, const GConfSchema* val, GError** err) {
	static gboolean (*gconf_engine_set_schemaORIG)(GConfEngine* conf, const gchar* key, const GConfSchema* val, GError** err);

	if (!gconf_engine_set_schemaORIG) {
		gconf_engine_set_schemaORIG = (gboolean(*)(GConfEngine* conf, const gchar* key, const GConfSchema* val, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_set_schema");
	}
	trace_gconf("gconf_engine_set_schema", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_set_schemaORIG(conf, key, val, err);
}

 gboolean gconf_engine_set_list(GConfEngine* conf, const gchar* key, GConfValueType list_type, GSList* list, GError** err) {
	static gboolean (*gconf_engine_set_listORIG)(GConfEngine* conf, const gchar* key, GConfValueType list_type, GSList* list, GError** err);

	if (!gconf_engine_set_listORIG) {
		gconf_engine_set_listORIG = (gboolean(*)(GConfEngine* conf, const gchar* key, GConfValueType list_type, GSList* list, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_set_list");
	}
	trace_gconf("gconf_engine_set_list", GCONF_CMD_SET_VALUE_LIST, key, list_type, (const char *)list);
	return gconf_engine_set_listORIG(conf, key, list_type, list, err);
}

 gboolean gconf_engine_set_pair(GConfEngine* conf, const gchar* key, GConfValueType car_type, GConfValueType cdr_type, gconstpointer address_of_car, gconstpointer address_of_cdr, GError** err) {
	static gboolean (*gconf_engine_set_pairORIG)(GConfEngine* conf, const gchar* key, GConfValueType car_type, GConfValueType cdr_type, gconstpointer address_of_car, gconstpointer address_of_cdr, GError** err);

	if (!gconf_engine_set_pairORIG) {
		gconf_engine_set_pairORIG = (gboolean(*)(GConfEngine* conf, const gchar* key, GConfValueType car_type, GConfValueType cdr_type, gconstpointer address_of_car, gconstpointer address_of_cdr, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_set_pair");
	}
	trace_gconf("gconf_engine_set_pair", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_set_pairORIG(conf, key, car_type, cdr_type, address_of_car, address_of_cdr, err);
}

 gboolean gconf_string_to_enum(GConfEnumStringPair lookup_table[], const gchar* str, gint* enum_value_retloc) {
	static gboolean (*gconf_string_to_enumORIG)(GConfEnumStringPair lookup_table[], const gchar* str, gint* enum_value_retloc);

	if (!gconf_string_to_enumORIG) {
		gconf_string_to_enumORIG = (gboolean(*)(GConfEnumStringPair lookup_table[], const gchar* str, gint* enum_value_retloc)) dlsym(RTLD_NEXT, "gconf_string_to_enum");
	}
	trace_gconf("gconf_string_to_enum", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_string_to_enumORIG(lookup_table, str, enum_value_retloc);
}

const gchar* gconf_enum_to_string(GConfEnumStringPair lookup_table[], gint enum_value) {
	static gchar* (*gconf_enum_to_stringORIG)(GConfEnumStringPair lookup_table[], gint enum_value);

	if (!gconf_enum_to_stringORIG) {
		gconf_enum_to_stringORIG = (gchar*(*)(GConfEnumStringPair lookup_table[], gint enum_value)) dlsym(RTLD_NEXT, "gconf_enum_to_string");
	}
	trace_gconf("gconf_enum_to_string", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_enum_to_stringORIG(lookup_table, enum_value);
}

 int gconf_debug_shutdown() {
	static int (*gconf_debug_shutdownORIG)();

	if (!gconf_debug_shutdownORIG) {
		gconf_debug_shutdownORIG = (int(*)()) dlsym(RTLD_NEXT, "gconf_debug_shutdown");
	}
	trace_gconf("gconf_debug_shutdown", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_debug_shutdownORIG();
}

 gboolean gconf_init(int argc, char** argv, GError** err) {
	static gboolean (*gconf_initORIG)(int argc, char** argv, GError** err);

	if (!gconf_initORIG) {
		gconf_initORIG = (gboolean(*)(int argc, char** argv, GError** err)) dlsym(RTLD_NEXT, "gconf_init");
	}
	trace_gconf("gconf_init", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_initORIG(argc, argv, err);
}

 gboolean gconf_is_initialized() {
	static gboolean (*gconf_is_initializedORIG)();

	if (!gconf_is_initializedORIG) {
		gconf_is_initializedORIG = (gboolean(*)()) dlsym(RTLD_NEXT, "gconf_is_initialized");
	}
	trace_gconf("gconf_is_initialized", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_is_initializedORIG();
}

 void gconf_preinit(gpointer app, gpointer mod_info) {
	static void (*gconf_preinitORIG)(gpointer app, gpointer mod_info);

	if (!gconf_preinitORIG) {
		gconf_preinitORIG = (void(*)(gpointer app, gpointer mod_info)) dlsym(RTLD_NEXT, "gconf_preinit");
	}
	trace_gconf("gconf_preinit", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_preinitORIG(app, mod_info);
}

 void gconf_postinit(gpointer app, gpointer mod_info) {
	static void (*gconf_postinitORIG)(gpointer app, gpointer mod_info);

	if (!gconf_postinitORIG) {
		gconf_postinitORIG = (void(*)(gpointer app, gpointer mod_info)) dlsym(RTLD_NEXT, "gconf_postinit");
	}
	trace_gconf("gconf_postinit", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_postinitORIG(app, mod_info);
}

 void gconf_clear_cache(GConfEngine* conf, GError** err) {
	static void (*gconf_clear_cacheORIG)(GConfEngine* conf, GError** err);

	if (!gconf_clear_cacheORIG) {
		gconf_clear_cacheORIG = (void(*)(GConfEngine* conf, GError** err)) dlsym(RTLD_NEXT, "gconf_clear_cache");
	}
	trace_gconf("gconf_clear_cache", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_clear_cacheORIG(conf, err);
}

 void gconf_synchronous_sync(GConfEngine* conf, GError** err) {
	static void (*gconf_synchronous_syncORIG)(GConfEngine* conf, GError** err);

	if (!gconf_synchronous_syncORIG) {
		gconf_synchronous_syncORIG = (void(*)(GConfEngine* conf, GError** err)) dlsym(RTLD_NEXT, "gconf_synchronous_sync");
	}
	trace_gconf("gconf_synchronous_sync", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_synchronous_syncORIG(conf, err);
}

 GConfValue* gconf_engine_get_full(GConfEngine* conf, const gchar* key, const gchar* locale, gboolean use_schema_default, gboolean* is_default_p, gboolean* is_writable_p, GError** err) {
	static GConfValue* (*gconf_engine_get_fullORIG)(GConfEngine* conf, const gchar* key, const gchar* locale, gboolean use_schema_default, gboolean* is_default_p, gboolean* is_writable_p, GError** err);

	if (!gconf_engine_get_fullORIG) {
		gconf_engine_get_fullORIG = (GConfValue*(*)(GConfEngine* conf, const gchar* key, const gchar* locale, gboolean use_schema_default, gboolean* is_default_p, gboolean* is_writable_p, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_full");
	}
	trace_gconf("gconf_engine_get_full", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_fullORIG(conf, key, locale, use_schema_default, is_default_p, is_writable_p, err);
}

 GConfEngine* gconf_engine_get_default() {
	static GConfEngine* (*gconf_engine_get_defaultORIG)();

	if (!gconf_engine_get_defaultORIG) {
		gconf_engine_get_defaultORIG = (GConfEngine*(*)()) dlsym(RTLD_NEXT, "gconf_engine_get_default");
	}
	trace_gconf("gconf_engine_get_default", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_defaultORIG();
}

 GConfEngine* gconf_engine_get_for_address(const gchar* address, GError** err) {
	static GConfEngine* (*gconf_engine_get_for_addressORIG)(const gchar* address, GError** err);

	if (!gconf_engine_get_for_addressORIG) {
		gconf_engine_get_for_addressORIG = (GConfEngine*(*)(const gchar* address, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_for_address");
	}
	trace_gconf("gconf_engine_get_for_address", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_for_addressORIG(address, err);
}

 GConfEngine* gconf_engine_get_for_addresses(GSList* addresses, GError** err) {
	static GConfEngine* (*gconf_engine_get_for_addressesORIG)(GSList* addresses, GError** err);

	if (!gconf_engine_get_for_addressesORIG) {
		gconf_engine_get_for_addressesORIG = (GConfEngine*(*)(GSList* addresses, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_for_addresses");
	}
	trace_gconf("gconf_engine_get_for_addresses", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_for_addressesORIG(addresses, err);
}

 void gconf_engine_unref(GConfEngine* conf) {
	static void (*gconf_engine_unrefORIG)(GConfEngine* conf);

	if (!gconf_engine_unrefORIG) {
		gconf_engine_unrefORIG = (void(*)(GConfEngine* conf)) dlsym(RTLD_NEXT, "gconf_engine_unref");
	}
	trace_gconf("gconf_engine_unref", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_unrefORIG(conf);
}

 void gconf_engine_ref(GConfEngine* conf) {
	static void (*gconf_engine_refORIG)(GConfEngine* conf);

	if (!gconf_engine_refORIG) {
		gconf_engine_refORIG = (void(*)(GConfEngine* conf)) dlsym(RTLD_NEXT, "gconf_engine_ref");
	}
	trace_gconf("gconf_engine_ref", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_refORIG(conf);
}

 GConfEngine* gconf_engine_get_local(const char* address, GError** err) {
	static GConfEngine* (*gconf_engine_get_localORIG)(const char* address, GError** err);

	if (!gconf_engine_get_localORIG) {
		gconf_engine_get_localORIG = (GConfEngine*(*)(const char* address, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_local");
	}
	trace_gconf("gconf_engine_get_local", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_localORIG(address, err);
}

 GConfEngine* gconf_engine_get_local_for_addresses(GSList* addresses, GError** err) {
	static GConfEngine* (*gconf_engine_get_local_for_addressesORIG)(GSList* addresses, GError** err);

	if (!gconf_engine_get_local_for_addressesORIG) {
		gconf_engine_get_local_for_addressesORIG = (GConfEngine*(*)(GSList* addresses, GError** err)) dlsym(RTLD_NEXT, "gconf_engine_get_local_for_addresses");
	}
	trace_gconf("gconf_engine_get_local_for_addresses", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_local_for_addressesORIG(addresses, err);
}

 void gconf_engine_set_user_data(GConfEngine* engine, gpointer data, GDestroyNotify dnotify) {
	static void (*gconf_engine_set_user_dataORIG)(GConfEngine* engine, gpointer data, GDestroyNotify dnotify);

	if (!gconf_engine_set_user_dataORIG) {
		gconf_engine_set_user_dataORIG = (void(*)(GConfEngine* engine, gpointer data, GDestroyNotify dnotify)) dlsym(RTLD_NEXT, "gconf_engine_set_user_data");
	}
	trace_gconf("gconf_engine_set_user_data", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_set_user_dataORIG(engine, data, dnotify);
}

 gpointer gconf_engine_get_user_data(GConfEngine* engine) {
	static gpointer (*gconf_engine_get_user_dataORIG)(GConfEngine* engine);

	if (!gconf_engine_get_user_dataORIG) {
		gconf_engine_get_user_dataORIG = (gpointer(*)(GConfEngine* engine)) dlsym(RTLD_NEXT, "gconf_engine_get_user_data");
	}
	trace_gconf("gconf_engine_get_user_data", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_engine_get_user_dataORIG(engine);
}

 GConfSchema* gconf_schema_new() {
	static GConfSchema* (*gconf_schema_newORIG)();

	if (!gconf_schema_newORIG) {
		gconf_schema_newORIG = (GConfSchema*(*)()) dlsym(RTLD_NEXT, "gconf_schema_new");
	}
	trace_gconf("gconf_schema_new", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_newORIG();
}

 void gconf_schema_free(GConfSchema* sc) {
	static void (*gconf_schema_freeORIG)(GConfSchema* sc);

	if (!gconf_schema_freeORIG) {
		gconf_schema_freeORIG = (void(*)(GConfSchema* sc)) dlsym(RTLD_NEXT, "gconf_schema_free");
	}
	trace_gconf("gconf_schema_free", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_freeORIG(sc);
}

 GConfSchema* gconf_schema_copy(const GConfSchema* sc) {
	static GConfSchema* (*gconf_schema_copyORIG)(const GConfSchema* sc);

	if (!gconf_schema_copyORIG) {
		gconf_schema_copyORIG = (GConfSchema*(*)(const GConfSchema* sc)) dlsym(RTLD_NEXT, "gconf_schema_copy");
	}
	trace_gconf("gconf_schema_copy", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_copyORIG(sc);
}

 void gconf_schema_set_type(GConfSchema* sc, GConfValueType type) {
	static void (*gconf_schema_set_typeORIG)(GConfSchema* sc, GConfValueType type);

	if (!gconf_schema_set_typeORIG) {
		gconf_schema_set_typeORIG = (void(*)(GConfSchema* sc, GConfValueType type)) dlsym(RTLD_NEXT, "gconf_schema_set_type");
	}
	trace_gconf("gconf_schema_set_type", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_set_typeORIG(sc, type);
}

 void gconf_schema_set_list_type(GConfSchema* sc, GConfValueType type) {
	static void (*gconf_schema_set_list_typeORIG)(GConfSchema* sc, GConfValueType type);

	if (!gconf_schema_set_list_typeORIG) {
		gconf_schema_set_list_typeORIG = (void(*)(GConfSchema* sc, GConfValueType type)) dlsym(RTLD_NEXT, "gconf_schema_set_list_type");
	}
	trace_gconf("gconf_schema_set_list_type", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_set_list_typeORIG(sc, type);
}

 void gconf_schema_set_car_type(GConfSchema* sc, GConfValueType type) {
	static void (*gconf_schema_set_car_typeORIG)(GConfSchema* sc, GConfValueType type);

	if (!gconf_schema_set_car_typeORIG) {
		gconf_schema_set_car_typeORIG = (void(*)(GConfSchema* sc, GConfValueType type)) dlsym(RTLD_NEXT, "gconf_schema_set_car_type");
	}
	trace_gconf("gconf_schema_set_car_type", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_set_car_typeORIG(sc, type);
}

 void gconf_schema_set_cdr_type(GConfSchema* sc, GConfValueType type) {
	static void (*gconf_schema_set_cdr_typeORIG)(GConfSchema* sc, GConfValueType type);

	if (!gconf_schema_set_cdr_typeORIG) {
		gconf_schema_set_cdr_typeORIG = (void(*)(GConfSchema* sc, GConfValueType type)) dlsym(RTLD_NEXT, "gconf_schema_set_cdr_type");
	}
	trace_gconf("gconf_schema_set_cdr_type", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_set_cdr_typeORIG(sc, type);
}

 void gconf_schema_set_locale(GConfSchema* sc, const gchar* locale) {
	static void (*gconf_schema_set_localeORIG)(GConfSchema* sc, const gchar* locale);

	if (!gconf_schema_set_localeORIG) {
		gconf_schema_set_localeORIG = (void(*)(GConfSchema* sc, const gchar* locale)) dlsym(RTLD_NEXT, "gconf_schema_set_locale");
	}
	trace_gconf("gconf_schema_set_locale", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_set_localeORIG(sc, locale);
}

 void gconf_schema_set_gettext_domain(GConfSchema* sc, const gchar* domain) {
	static void (*gconf_schema_set_gettext_domainORIG)(GConfSchema* sc, const gchar* domain);

	if (!gconf_schema_set_gettext_domainORIG) {
		gconf_schema_set_gettext_domainORIG = (void(*)(GConfSchema* sc, const gchar* domain)) dlsym(RTLD_NEXT, "gconf_schema_set_gettext_domain");
	}
	trace_gconf("gconf_schema_set_gettext_domain", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_set_gettext_domainORIG(sc, domain);
}

 void gconf_schema_set_short_desc(GConfSchema* sc, const gchar* desc) {
	static void (*gconf_schema_set_short_descORIG)(GConfSchema* sc, const gchar* desc);

	if (!gconf_schema_set_short_descORIG) {
		gconf_schema_set_short_descORIG = (void(*)(GConfSchema* sc, const gchar* desc)) dlsym(RTLD_NEXT, "gconf_schema_set_short_desc");
	}
	trace_gconf("gconf_schema_set_short_desc", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_set_short_descORIG(sc, desc);
}

 void gconf_schema_set_long_desc(GConfSchema* sc, const gchar* desc) {
	static void (*gconf_schema_set_long_descORIG)(GConfSchema* sc, const gchar* desc);

	if (!gconf_schema_set_long_descORIG) {
		gconf_schema_set_long_descORIG = (void(*)(GConfSchema* sc, const gchar* desc)) dlsym(RTLD_NEXT, "gconf_schema_set_long_desc");
	}
	trace_gconf("gconf_schema_set_long_desc", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_set_long_descORIG(sc, desc);
}

 void gconf_schema_set_owner(GConfSchema* sc, const gchar* owner) {
	static void (*gconf_schema_set_ownerORIG)(GConfSchema* sc, const gchar* owner);

	if (!gconf_schema_set_ownerORIG) {
		gconf_schema_set_ownerORIG = (void(*)(GConfSchema* sc, const gchar* owner)) dlsym(RTLD_NEXT, "gconf_schema_set_owner");
	}
	trace_gconf("gconf_schema_set_owner", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_set_ownerORIG(sc, owner);
}

 void gconf_schema_set_default_value(GConfSchema* sc, const GConfValue* val) {
	static void (*gconf_schema_set_default_valueORIG)(GConfSchema* sc, const GConfValue* val);

	if (!gconf_schema_set_default_valueORIG) {
		gconf_schema_set_default_valueORIG = (void(*)(GConfSchema* sc, const GConfValue* val)) dlsym(RTLD_NEXT, "gconf_schema_set_default_value");
	}
	trace_gconf("gconf_schema_set_default_value", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_set_default_valueORIG(sc, val);
}

 void gconf_schema_set_default_value_nocopy(GConfSchema* sc, GConfValue* val) {
	static void (*gconf_schema_set_default_value_nocopyORIG)(GConfSchema* sc, GConfValue* val);

	if (!gconf_schema_set_default_value_nocopyORIG) {
		gconf_schema_set_default_value_nocopyORIG = (void(*)(GConfSchema* sc, GConfValue* val)) dlsym(RTLD_NEXT, "gconf_schema_set_default_value_nocopy");
	}
	trace_gconf("gconf_schema_set_default_value_nocopy", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_set_default_value_nocopyORIG(sc, val);
}

 GConfValueType gconf_schema_get_type(const GConfSchema* schema) {
	static GConfValueType (*gconf_schema_get_typeORIG)(const GConfSchema* schema);

	if (!gconf_schema_get_typeORIG) {
		gconf_schema_get_typeORIG = (GConfValueType(*)(const GConfSchema* schema)) dlsym(RTLD_NEXT, "gconf_schema_get_type");
	}
	trace_gconf("gconf_schema_get_type", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_get_typeORIG(schema);
}

 GConfValueType gconf_schema_get_list_type(const GConfSchema* schema) {
	static GConfValueType (*gconf_schema_get_list_typeORIG)(const GConfSchema* schema);

	if (!gconf_schema_get_list_typeORIG) {
		gconf_schema_get_list_typeORIG = (GConfValueType(*)(const GConfSchema* schema)) dlsym(RTLD_NEXT, "gconf_schema_get_list_type");
	}
	trace_gconf("gconf_schema_get_list_type", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_get_list_typeORIG(schema);
}

 GConfValueType gconf_schema_get_car_type(const GConfSchema* schema) {
	static GConfValueType (*gconf_schema_get_car_typeORIG)(const GConfSchema* schema);

	if (!gconf_schema_get_car_typeORIG) {
		gconf_schema_get_car_typeORIG = (GConfValueType(*)(const GConfSchema* schema)) dlsym(RTLD_NEXT, "gconf_schema_get_car_type");
	}
	trace_gconf("gconf_schema_get_car_type", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_get_car_typeORIG(schema);
}

 GConfValueType gconf_schema_get_cdr_type(const GConfSchema* schema) {
	static GConfValueType (*gconf_schema_get_cdr_typeORIG)(const GConfSchema* schema);

	if (!gconf_schema_get_cdr_typeORIG) {
		gconf_schema_get_cdr_typeORIG = (GConfValueType(*)(const GConfSchema* schema)) dlsym(RTLD_NEXT, "gconf_schema_get_cdr_type");
	}
	trace_gconf("gconf_schema_get_cdr_type", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_get_cdr_typeORIG(schema);
}

const char* gconf_schema_get_locale(const GConfSchema* schema) {
	static char* (*gconf_schema_get_localeORIG)(const GConfSchema* schema);

	if (!gconf_schema_get_localeORIG) {
		gconf_schema_get_localeORIG = (char*(*)(const GConfSchema* schema)) dlsym(RTLD_NEXT, "gconf_schema_get_locale");
	}
	trace_gconf("gconf_schema_get_locale", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_get_localeORIG(schema);
}

const char* gconf_schema_get_gettext_domain(const GConfSchema* schema) {
	static char* (*gconf_schema_get_gettext_domainORIG)(const GConfSchema* schema);

	if (!gconf_schema_get_gettext_domainORIG) {
		gconf_schema_get_gettext_domainORIG = (char*(*)(const GConfSchema* schema)) dlsym(RTLD_NEXT, "gconf_schema_get_gettext_domain");
	}
	trace_gconf("gconf_schema_get_gettext_domain", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_get_gettext_domainORIG(schema);
}

const char* gconf_schema_get_short_desc(const GConfSchema* schema) {
	static char* (*gconf_schema_get_short_descORIG)(const GConfSchema* schema);

	if (!gconf_schema_get_short_descORIG) {
		gconf_schema_get_short_descORIG = (char*(*)(const GConfSchema* schema)) dlsym(RTLD_NEXT, "gconf_schema_get_short_desc");
	}
	trace_gconf("gconf_schema_get_short_desc", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_get_short_descORIG(schema);
}

const char* gconf_schema_get_long_desc(const GConfSchema* schema) {
	static char* (*gconf_schema_get_long_descORIG)(const GConfSchema* schema);

	if (!gconf_schema_get_long_descORIG) {
		gconf_schema_get_long_descORIG = (char*(*)(const GConfSchema* schema)) dlsym(RTLD_NEXT, "gconf_schema_get_long_desc");
	}
	trace_gconf("gconf_schema_get_long_desc", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_get_long_descORIG(schema);
}

const char* gconf_schema_get_owner(const GConfSchema* schema) {
	static char* (*gconf_schema_get_ownerORIG)(const GConfSchema* schema);

	if (!gconf_schema_get_ownerORIG) {
		gconf_schema_get_ownerORIG = (char*(*)(const GConfSchema* schema)) dlsym(RTLD_NEXT, "gconf_schema_get_owner");
	}
	trace_gconf("gconf_schema_get_owner", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_get_ownerORIG(schema);
}

 GConfValue* gconf_schema_get_default_value(const GConfSchema* schema) {
	static GConfValue* (*gconf_schema_get_default_valueORIG)(const GConfSchema* schema);

	if (!gconf_schema_get_default_valueORIG) {
		gconf_schema_get_default_valueORIG = (GConfValue*(*)(const GConfSchema* schema)) dlsym(RTLD_NEXT, "gconf_schema_get_default_value");
	}
	trace_gconf("gconf_schema_get_default_value", GCONF_CMD_UNKNOWN, NULL, GCONF_VALUE_INVALID, NULL);
	return gconf_schema_get_default_valueORIG(schema);
}

void __attribute__ ((constructor)) lib_init(void);
void __attribute__ ((destructor)) lib_finish(void);


void lib_init()
{
	char *env = NULL;
	char procname[256];
	char *pch = NULL;
	char *backtrace = NULL;

	if (trace_file_name[0] == '\0') {
		env = getenv("GCONF_TRACE_DIR");
		get_proc_name(getpid(), procname);
		pch = strrchr(procname, '/');
		if (pch)
			memmove(procname, pch, procname + strlen(procname) - pch + 1);
		if (env)
			sprintf(trace_file_name, "%s/%s.log", env, procname);
		fprintf(stderr, "trace_file_name:%s\n", trace_file_name);
	} if (sem_init(&lock, 0, 1) == -1)
		fprintf(stderr, "%s:sem_init failed\n", __FUNCTION__);
	backtrace = getenv("GCONF_BACKTRACE");	
	if (backtrace)
		prt_backtrace = atoi(backtrace);
}

void lib_finish()
{
	sem_destroy(&lock);
}

